name: geo_flutter_fire
description: GeoFlutterFire is an open-source library that allows you to store
  and query firestore documents based on their geographic location.
version: 3.0.6
homepage: https://github.com/OttomanDeveloper/geo_flutter_fire

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  cloud_firestore: ^3.4.4
  flutter:
    sdk: flutter
  rxdart: ^0.27.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
