name: geo_flutter_fire
description: GeoFlutterFire is an open-source library that allows you to store
  and query firestore documents based on their geographic location.
version: 3.0.8
homepage: https://github.com/OttomanDeveloper/geo_flutter_fire

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  cloud_firestore: ^4.8.2
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
